Sender dokumentdata fra Frisinn
navikt/k9-sak-web pull request #1028
Opened 2020-10-07 06:41 UTC by TomasEng

2020-10-09 11:56 UTC, tor-nav requested changes

2020-10-09 11:56 UTC, tor-nav commented on packages/prosess-vedtak/src/components/VedtakPanels.jsx
> +  behandlingApi,
Eg meinar sterkt at ein ikkje skal senda med behandlingApi med ned til proseess/fakta-panela. Sånn vil eg iallfall ikkje ha det i fpsak. Da får desse komponentane ein avhengigheit dei ikkje bør ha. Send heller med ned ein callback. 

Kanskje ein endrar dette på sikt, sånn at dei ulike panelkomponentane sjølv hentar dataen dei treng, men sånn er det ingen andre stader no

2020-10-09 11:56 UTC, tor-nav commented on packages/behandling-felles/src/components/ProsessStegPanel.tsx
> +                    behandlingApi,
ikkje send med behandlingApi her. (Sjå begrunnelse annan stad)

2020-10-09 11:56 UTC, tor-nav commented on packages/behandling-felles/src/components/ProsessStegPanel.tsx
> +                    featureToggles,
kan du ikkje heller senda med featureToggles til den aktuelle komponenten (i staden for å senda til alle her)

2020-10-09 11:56 UTC, tor-nav commented on packages/prosess-vedtak/src/components/revurdering/VedtakRevurderingForm.jsx
> +      onChange(values, dispatch, props) {
Kvifor gjer ein kall til DOKUMENTDATA_LAGRE både her og under lagring av aksjonspunkt? (Eg anar ikkje kva hensikten med dette kallet er altso)

2020-10-15 10:59 UTC, tor-nav approved these changes

2020-10-15 10:59 UTC, tor-nav commented on packages/behandling-felles/src/components/ProsessStegPanel.tsx
> +  dokumentdata?: {};
kan denne fjernast?

2020-10-15 11:03 UTC, TomasEng commented on packages/behandling-felles/src/components/ProsessStegPanel.tsx
> +  dokumentdata?: {};
Den er ikke nødvendig nei

2020-10-15 11:51 UTC, merged